version: "3"

services:
  ee-svg:
    build: ./
    container_name: ee-svg
    image: ee-svg
    networks: []
    volumes:
      - ./:/workdir/
    # command: sh -c "find . -maxdepth 1 -name \*.tex -exec pdflatex -shell-escape {} \; && rm -f *.aux && rm -f *.log"