version: "3"

services:
  latex-alpine:
    build:
      context: ./
      args:
        LATEX_PACKAGES: latexmk xkeyval standalone pgf xstring xcolor siunitx circuitikz
    container_name: latex-alpine
    image: latex-alpine
    networks: []
    volumes:
      - ./:/workdir/
    command: sh -c "latexmk -pdf && latexmk -c && find . -maxdepth 1 -name \*.pdf -exec pdf2svg {} {}.svg \;"